language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.3
      brew_packages: zeromq
    - os: osx
      disable_homebrew: true      
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - libzmq3-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
